#!/usr/bin/php
<?php
# Copyright (c) 2012-2013 Colin Williams / University of Southampton
# License: GPL

# This file is part of Event Feed Aggregator.

# Event Feed Aggregator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Event Feed Aggregator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Event Feed Aggregator.  If not, see <http://www.gnu.org/licenses/>.

global $diary_config;
$diary_config["path"] = dirname(dirname(__FILE__));
require($diary_config["path"].'/etc/config.php');
include $diary_config["path"].'/lib/scraper-utils.php';

initialiseScraper();

// Get the RSS data from the Feed URL.
list($rss, $sourcedocuments) = getRSS($options->FeedURL);

if($rss != null && $rss->channel != null && $rss->channel->item != null)
{
	foreach($rss->channel->item as $item)
	{
		// Process the event.
		$data[] = processItem($item, $options, $sourcedocuments);
	}
}

// Output the data as XML.
echo generateEventXML($data, $sourcedocuments, $issues);

/**
 * Process a single event.
 *
 * @param	object	$item		The item to process.
 * @param	array	$options	The options passed to this script.
 */
function process($item, $options, $sourcedocuments)
{
	$title = trim($item->title);
	$pdate = array();
	if(preg_match('/^([A-Z][a-z]+day), ([12]?[0-9])[a-z][a-z] ([A-Z][a-z]+) (20[0-9][0-9]) - (1?[0-9]:[0-5][0-9][ap]m) (.*) (in|at) (.*)$/', $title, $matches))
	{
		$wday = $matches[1];
		$day = $matches[2];
		$month = $matches[3];
		$year = $matches[4];
		$time = $matches[5];
		$title = $matches[6];
		$location = $matches[8];
		
		$tmp = strtotime("$day $month $year $time");

		$pdate = array(array('from' => date('c', $tmp)));
	}
	
	$desc = trim($item->description);

	$res = array(
		'title'		=> $title,
		'link'		=> (string)$item->guid,
		'date'		=> $pdate,
		'desc'		=> $desc,
		'feedName'	=> (string)$options->FeedName,
		'type'		=> (string)$options->Type,
		'feedID'	=> (string)$options->FeedID,
		'host'		=> (string)$options->FacultyUnitGroup,
		'tags'		=> explode(" ", $options->Tags),
		'sourceDocuments' => $sourcedocuments,
	);
	if(isset($location))
	{
		$venuelink = getVenueLink($location);
		if($location != "")
		{
			$res['venue'] = $location;
		}
		if($venuelink != "")
		{
			$res['venuelink'] = $venuelink;
		}
	}
	return $res;
}

